#   music.py

# For os stuff
import os

# Discord related stuff
from discord.ext import commands
from discord import app_commands
import discord

# YTDLP library to stream the music from youtube 
import yt_dlp

# GET FFMPEG_EXECUTABLE LOCATION FROM LOCAL ENVIRONMENT
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
from dotenv import load_dotenv
load_dotenv()
FFMPEG_EXECUTABLE = os.getenv("FFMPEG_PATH")
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# YTDLP Source class to treat music stream as PCM audio
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
class Source:
    # Options for YTDL
    YTDL_OPTIONS = {
        'format': 'bestaudio/best', # Best audio format
        'noplaylist': 'True' # Don't accept playlists
    }

    # Options for FFmpeg postprocessor
    FFMPEG_OPTIONS = {
        'options': '-vn',       # Verbose, no-overwrite
        'executable':FFMPEG_EXECUTABLE,
        'before_options': '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5'
    }

    # IMPORTANT: Create a YTDL Instance with given OPTIONS
    ytdl = yt_dlp.YoutubeDL(YTDL_OPTIONS) # NOTE: is this just ytdl?

    


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Queue class serves sources to the player
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
class Queue:
    


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# The music Cog containing all the app commands
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
class Music(commands.Cog):

    def __init__(self, client) -> None:
        self.client = client

        # IMPORTANT members:
        self.is_playing = False
        self.voice_channel = None

    @app_commands.command(name="test")
    async def command(self, interaction: discord.Interaction) -> None:
        """ Command description for the autogenerated help function """
        await interaction.response.send_message("Interaction response", ephemeral=False)

async def setup(client: commands.Bot) -> None:
    try:
        await client.add_cog(Music(client))
        print ("[OK]")
    except:
        print ("[ERROR]")

