#   template.py

from discord.ext import commands
from discord import app_commands
import discord

# Commands and events for greeting users
class Template(commands.Cog):

    def __init__(self, client) -> None:
        self.client = client

    @app_commands.command(name="test")
    async def command(self, interaction: discord.Interaction) -> None:
        """ Command description for the autogenerated help function """
        await interaction.response.send_message("Interaction response", ephemeral=False)

async def setup(client: commands.Bot) -> None:
    try:
        await client.add_cog(Template(client))
        print ("[OK]")
    except:
        print ("[ERROR]")

